// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyglbutqfkaidvtkujwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5Z2xidXRxZmthaWR2dGt1andoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTk2MzYsImV4cCI6MjA2MjEzNTYzNn0.lvV5xbJ5NSGPl2qf2ix-4T10GuT_7-cCkGSmQyDzIf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);